[general]

HOME_DIR=./users/default/
_TERM_RESOLUTION=LOW
_RETROPROFILE=vt220-green
_TERM_MOUSE_SHOW=disable


[settings]

# === LOGIN ===

LOGIN_SCREEN=enable
LOGIN_MENU=enable

# === SHADER ===

_TERM_SHADER=enable
SHADER_QUALITY=MEDIUM

# === OVERLAY ===
# In case screen scaling 1x, 2x, ... is used, it is recommended to tune
# below OVERLAY_WIDTH and OVERLAY_HEIGHT when running BUDOSTACK through
# ./apps/terminal.

_TERM_OVERLAY=enable
OVERLAY_WIDTH = 1565     # 100% scaling (default)
OVERLAY_HEIGHT = 830     # 100% scaling (default)
OVERLAY_OFFSET_X = -3    # 100% scaling (default)
OVERLAY_OFFSET_Y = 27    # 100% scaling (default)
#OVERLAY_WIDTH = 2075     # 200% scaling
#OVERLAY_HEIGHT = 1102    # 200% scaling
#OVERLAY_OFFSET_X = 3    # 200% scaling
#OVERLAY_OFFSET_Y = 35    # 200% scaling

# === SOUND ===

_TERM_TYPING_SOUND=enable
_TERM_TYPING_VOLUME=50
_TERM_BACKGROUND_SOUND=enable
_TERM_BACKGROUND_VOLUME=75
