

[general]

# Default environment settings

HOME_DIR=./users/default/
_TERM_RESOLUTION=HIGH                # LOW: 320x240; HIGH: 640x480
_RETROPROFILE=ibm5150
_TERM_MOUSE_SHOW=disable


[settings]

# Simulation Settings:

SIMULATION_MODE = enable             # enable | disable

# Shader Settings:

_TERM_SHADER = enable                # enable | disable
SHADER_QUALITY = MEDIUM              # LOW | MEDIUM | HIGH (eats battery)

# Overlay Settings:

_TERM_OVERLAY = disable               # enable | disable
_TERM_OVERLAY_ZOOM = 150
_TERM_OVERLAY_OFFSET_X = 3.16
_TERM_OVERLAY_OFFSET_Y = 11.0

# Terminal Settings:

_TERM_LAYOUT_ASPECT = 4:3            # 4:3 | 5:4 | 16:9
_TERM_MARGIN = 5                     # Pixels
TERMINAL_WIDTH = 57.1875             # Percents from current resolution
TERMINAL_HEIGHT = 57.1875            # ...
TERMINAL_OFFSET_X = 0                # ...
TERMINAL_OFFSET_Y = 1.171875         # ...

# Sound Settings:

_TERM_TYPING_SOUND = enable          # enable | disable
_TERM_TYPING_VOLUME = 50             # 0...100%
_TERM_BACKGROUND_SOUND = enable      # enable | disable
_TERM_BACKGROUND_VOLUME = 75         # 0...100%


[variables]

# Used for system state tracking do not change

VAR_FIRST_BOOT = 1


