#include <stdio.h>
#include <stdlib.h>

static const char *manual[] = {
"BUDOSTACK C Programming Handbook",
"======================================================================",
"This guide is a university-level crash course in practical C. It blends",
"theory, runnable snippets, build instructions, and study prompts so you",
"can grow into a junior systems developer. Lines fit 78 columns for easy",
"paging and searching.",
"",
"Using this tool",
"---------------",
"- View with paging: utilities/chelp | less",
"- Full build check in this repo: make clean all",
"- Single-file compile template: cc -std=c11 -Wall -Wextra -Werror \\",
"  -Wpedantic -o demo demo.c",
"",
"Language in one paragraph",
"--------------------------",
"C is a small, compiled, procedural language with manual memory control.",
"Code lives in translation units (.c plus headers). The compiler creates",
"object files; the linker resolves symbols into executables or libraries.",
"You manipulate bytes, addresses, and system calls directly.",
"",
"Minimal program",
"----------------",
"#include <stdio.h>",
"",
"int main(void) {",
"    printf(\"Hello, world\\n\");",
"    return 0;",
"}",
"",
"Build pipeline",
"--------------",
"1. Preprocess: handle #include, #define, and conditional blocks.",
"2. Compile: translate C to object code (.o).",
"3. Link: combine objects and libraries into executables or archives.",
"4. Optional: static analysis, sanitizers, profilers, formatters.",
"",
"Core vocabulary",
"----------------",
"- Types: char, short, int, long, long long, float, double, _Bool, void.",
"- Widths vary by platform; use <stdint.h> for fixed widths (uint32_t).",
"- Qualifiers: const (read-only), volatile (can change unexpectedly).",
"- Signed vs unsigned: conversions matter; avoid mixing without casts.",
"",
"Literals and conversions",
"-------------------------",
"- Integer bases: 42, 052 (octal), 0x2A (hex).",
"- Suffixes: 1U (unsigned), 1L (long), 1ULL (unsigned long long).",
"- Char constants use single quotes; \\0 is the null terminator.",
"- Implicit conversions can truncate; prefer explicit casts when needed.",
"",
"Storage duration and linkage",
"-----------------------------",
"- Automatic: local variables live until block exit.",
"- Static duration: file-scope or static variables live for program life.",
"- Dynamic: malloc/calloc/realloc allocate; free releases.",
"- Linkage: extern symbols are visible across translation units; static",
"  limits visibility to the current file.",
"",
"Expressions and operators",
"--------------------------",
"- Arithmetic: + - * / % with integer or floating semantics.",
"- Comparison: == != < <= > >= return int 0 or 1.",
"- Logical: && || ! short-circuit; useful for guards.",
"- Bitwise: & | ^ ~ << >> for flags, masks, and packed data.",
"- Assignment: = and compound forms like += -= <<= etc.",
"- Ternary: cond ? a : b for small conditional expressions.",
"- Use parentheses to clarify precedence and intent.",
"",
"Control flow",
"-------------",
"- Branch: if / else if / else; switch with case, break, and default.",
"- Loops: for, while, do/while; break exits, continue skips ahead.",
"- goto is legal; reserve it for single-point cleanup in error paths.",
"",
"Functions",
"---------",
"- Declare prototypes before use to catch mismatches at compile time.",
"- Arguments pass by value; use pointers to let callees modify data.",
"- Document ownership: who allocates, who frees, and valid lifetimes.",
"- Static functions stay private to a translation unit; inline helpers",
"  in headers should be static inline with brief comments.",
"",
"Pointers",
"--------",
"- Pointers hold addresses; *p dereferences, &x yields an address.",
"- Always initialize pointers; set them to NULL after freeing.",
"- Pointer arithmetic steps in units of the pointed-to type.",
"- size_t for lengths, ptrdiff_t for pointer differences.",
"- Double pointers (T **p) let you modify caller-owned pointers.",
"",
"Arrays and decay",
"-----------------",
"- int a[4] = {1,2,3,4}; sizeof a is total bytes within its scope.",
"- Arrays decay to pointers when passed to functions; pass lengths too.",
"- Multidimensional arrays store contiguous rows; match parameter types",
"  exactly (int grid[3][4] or int (*grid)[4]).",
"",
"Strings",
"-------",
"- Strings are arrays of char ending with '\\0'.",
"- Keep space for the terminator when allocating or copying.",
"- Prefer snprintf and strnlen over unsafe strcpy/strlen on unknown data.",
"- Compare with strcmp/strncmp; never with == on pointers.",
"",
"Structs, unions, and enums",
"---------------------------",
"struct point { double x; double y; };",
"enum color { COLOR_RED, COLOR_GREEN, COLOR_BLUE };",
"union number { int i; double d; };",
"- Structs group fields; use designated initializers for clarity.",
"- Enums create named integer constants; great for switch statements.",
"- Unions overlay storage; track which member is active.",
"- Bit-fields: struct flags { unsigned ready:1; unsigned error:1; };",
"",
"Memory layout and alignment",
"----------------------------",
"- Alignment may add padding inside structs; order fields from widest to",
"  narrowest to reduce space.",
"- Use offsetof(type, field) from <stddef.h> for layout-sensitive code.",
"- Never assume sizeof(long) or pointer sizes across platforms.",
"",
"Dynamic memory",
"--------------",
"- malloc(size) allocates raw bytes; calloc(count, size) zero-initializes.",
"- realloc(ptr, new_size) resizes; on failure, the old block is preserved.",
"- Always check allocation results before use.",
"- Free in reverse ownership order; set freed pointers to NULL.",
"",
"Error handling",
"--------------",
"- Return EXIT_SUCCESS or EXIT_FAILURE from main for clarity.",
"- perror(label) prints errno-based errors for system/library calls.",
"- Use fprintf(stderr, ...) for custom diagnostics.",
"- Validate inputs aggressively to avoid undefined behaviour.",
"",
"Input and output",
"----------------",
"- stdin, stdout, stderr are FILE streams; line buffering applies to",
"  terminals. fflush(stdout) forces a flush.",
"- fgets(buffer, size, stdin) reads a line; check for NULL on EOF/error.",
"- fprintf/printf/scanf handle formatted text; match formats to types",
"  exactly (%zu for size_t, %p for void *, %lld for long long).",
"",
"Files",
"-----",
"- Open with fopen(path, mode). Modes: \"r\", \"w\", \"a\", plus b for binary.",
"- fread/fwrite for binary blocks; fprintf/fscanf for text.",
"- Always fclose on every path; check ferror and feof when looping.",
"",
"Command line arguments",
"----------------------",
"int main(int argc, char **argv) {",
"    for (int i = 0; i < argc; ++i)",
"        printf(\"arg %d: %s\\n\", i, argv[i]);",
"    return 0;",
"}",
"- argc counts arguments; argv is NULL-terminated for convenience.",
"",
"Header hygiene",
"--------------",
"- Use include guards (#ifndef FILE_H ... #endif) or #pragma once.",
"- Put declarations in headers and definitions in .c files.",
"- Keep headers self-contained: include what they need, not more.",
"- Expose only what callers require; keep helpers static in .c files.",
"",
"Macros and constants",
"---------------------",
"- Prefer enums or const variables for typed constants when possible.",
"- Use macros for compile-time configuration or simple wrappers.",
"- Parenthesize macro parameters to avoid precedence surprises.",
"- Example: #define ARRAY_LEN(x) (sizeof(x) / sizeof((x)[0]))",
"",
"Function pointers",
"------------------",
"- int (*op)(int, int) = add; lets you pass callbacks (qsort comparers).",
"- typedef helps readability: typedef int (*op_fn)(int, int);",
"- Common uses: callbacks, virtual tables, configurable strategies.",
"",
"Debugging",
"---------",
"- Add -g to compiler flags for debug symbols; run gdb ./a.out.",
"- Useful gdb commands: run, bt, frame N, print var, info locals, quit.",
"- printf-debugging works: label prints clearly and include newlines.",
"- Sanitizers: -fsanitize=address,undefined help catch memory issues.",
"",
"Testing mindset",
"---------------",
"- Test edge cases: empty strings, zero lengths, overflow boundaries.",
"- Use temporary files and controlled inputs for repeatable tests.",
"- Add #ifdef TEST blocks for self-checks without shipping test code.",
"",
"Practical example: safe line reader",
"-----------------------------------",
"#include <stdio.h>",
"#include <stdlib.h>",
"",
"int main(void) {",
"    char buf[128];",
"    while (fgets(buf, sizeof buf, stdin)) {",
"        if (buf[0] == '\\n') continue;",
"        printf(\"got: %s\", buf);",
"    }",
"    if (ferror(stdin)) {",
"        perror(\"read\");",
"        return EXIT_FAILURE;",
"    }",
"    return EXIT_SUCCESS;",
"}",
"",
"File copier exercise",
"---------------------",
"- Implement copy(src, dst) that opens src rb, dst wb, copies with",
"  fread/fwrite, checks errors, and closes both streams on all paths.",
"- Extend it to handle partial writes and to preserve permissions using",
"  stat/chmod on POSIX platforms.",
"",
"Algorithms and data structures",
"-------------------------------",
"- Practice arrays, linked lists, dynamic arrays, hash tables, and queues.",
"- Implement qsort-like comparators; stable sorts need custom logic.",
"- Understand complexity (O(n), O(n log n)) to reason about performance.",
"",
"Systems programming primers",
"----------------------------",
"- POSIX file descriptors: open, read, write, close for unbuffered I/O.",
"- Multiplexing: select/poll/epoll for many sockets (advanced study).",
"- Processes: fork, exec, wait for launching child programs.",
"- Threads: pthread_create, mutexes, condition variables for concurrency.",
"",
"Style and maintainability",
"-------------------------",
"- Match the house style: 4-space indents, K&R braces, clear comments.",
"- Keep functions short and cohesive; name things after behaviour.",
"- Avoid global state unless clearly documented.",
"- Limit line length to 78 columns for pager-friendly output.",
"",
"Code review checklist",
"----------------------",
"- Are inputs validated and errors reported with context?",
"- Are ownership and lifetimes obvious?",
"- Does every allocation, file, or lock have a matching cleanup?",
"- Are integer conversions explicit and safe?",
"- Did make clean all pass without warnings?",
"",
"Career and learning path",
"-------------------------",
"- Read: Kernighan & Ritchie, King, and POSIX.1-2008 manuals.",
"- Build a portfolio: small utilities, libraries, and tests under git.",
"- Contribute to BUDOSTACK apps/utilities to gain review experience.",
"- Practice explaining trade-offs in code reviews and documentation.",
"",
"Practice roadmap",
"-----------------",
"1. Recreate standard tools (wc, cat, cp) with robust error handling.",
"2. Write a simple allocator wrapper that logs allocations and frees.",
"3. Build a network echo server using sockets and select (advanced).",
"4. Profile hot paths with perf or gprof; optimize with measurements.",
"",
"Key format cheatsheet",
"---------------------",
"- printf: %d int, %u unsigned, %ld long, %zu size_t, %p void *.",
"- scanf:  %d int, %u unsigned, %ld long, %zu size_t, %p void *.",
"- Remember matching argument types is mandatory.",
"",
"Closing thought",
"---------------",
"This handbook is a starting point. Experiment, read existing BUDOSTACK",
"utilities, and keep a notebook of patterns, mistakes, and questions.",
"Curiosity plus disciplined testing will make you effective in C.",
"",
"Happy hacking!"
};

static void print_manual(void)
{
    const size_t lines = sizeof(manual) / sizeof(manual[0]);

    for (size_t i = 0; i < lines; ++i) {
        puts(manual[i]);
    }
}

int main(void)
{
    print_manual();
    return EXIT_SUCCESS;
}
